### ISSUE TITLE
As a user I want to save the state of all the windows that are open in MEW

### ISSUE THREAD

**Issue by bioinfbloke** [jpverhaeghe/cellexalvr#37]

**Comment by jpverhaeghe** [comment]
- [x] Look at JSON as potential way to save the data
- [x] Current text load/unload seems overly complex for this, so perhaps use the same folder but write own data grab and save system
- [x] Create label system that can be written/read easily to reset browser windows
- [ ] Pop-outs will need to save state, and that will probably have to wait for data from MDV

**Comment by jpverhaeghe** [comment]
Things that need saving for each main web page: 
- Probably won't be able to save the data where the scroll is in the page (or not right away - will need time to think on how to do this).

- [x] the URL currently loaded
- [x] position, rotation and scale (transform) in the world
- [ ] what pop-outs are open for this web page (for MDV pages only?)
- [ ] transforms for those pop-outs (perhaps a list)

Go through each main page, load it, then go through the list of pop-outs and open the pop-out by sending a message to the web client and then move the pop-out to the correct transform.
